### ISSUE TITLE
molgrid version?

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [devalab/DeepPocket#32]
Which version of molgrid is this running? I am running molgrid=0.1.1 and getting this error:

```
Traceback (most recent call last):
  File "predict.py", line 89, in <module>
    protein_gninatype=gninatype(protein_nowat_file)
  File "/content/fpocket/DeepPocket/types_and_gninatyper.py", line 20, in gninatype
    dataloader=molgrid.ExampleProvider(atom_map,shuffle=False,default_batch_size=1)
ValueError: Unknown keyword argument default_batch_size
```

Any idea how to fix this?

**Comment by RishalAggarwal** [comment]
could you try using a more updated version of molgrid?

**Comment by JavierSanchez-Utges** [comment]
I switched to 0.5.2 and that fixed the error. Thanks.
